apiVersion: v1
baseDomain: example.com  # The base domain for the cluster
metadata:
  name: my-cluster        # Name of your cluster
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3             # Number of worker nodes
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3             # Number of master nodes
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14   # CIDR for the cluster network
    hostPrefix: 23
  networkType: OpenShiftSDN # Or "OVNKubernetes" depending on your preference
  serviceNetwork:
  - 172.30.0.0/16         # CIDR for the service network
platform:
  vsphere:
    vCenter: "vcenter.example.com"  # vCenter FQDN or IP
    username: "administrator@vsphere.local"  # vCenter username
    password: "YourPassword"      # vCenter password (consider using a secret)
    datacenter: "Datacenter"      # vSphere datacenter name
    defaultDatastore: "Datastore" # Default datastore for VMs
    folder: "/datacenter/vm/folder" # Folder for VMs
    cluster: "ClusterName"        # vSphere cluster name
    network: "NetworkName"        # vSphere network name
    apiVIP: "192.168.1.10"        # Virtual IP for API
    ingressVIP: "192.168.1.11"    # Virtual IP for Ingress
pullSecret: '{"auths": ...}'      # Your Red Hat pull secret (replace with actual value)
sshKey: "ssh-rsa AAAA..."         # Your public SSH key for cluster access

